export const skins = [
  {
    id: 1,
    name: "Спайкли",
    type: "Стрелок",
    hp: 1200,
    attack: 180,
    defense: 40,
    price: 0,
    image: "img/skins/spikly.png",
  },
  {
    id: 2,
    name: "Буллит",
    type: "Танкист",
    hp: 2000,
    attack: 160,
    defense: 80,
    price: 150,
    image: "img/skins/bullit.png",
  },
  {
    id: 3,
    name: "Лунара",
    type: "Маг",
    hp: 1300,
    attack: 210,
    defense: 50,
    price: 200,
    image: "img/skins/lunara.png",
  },
  {
    id: 4,
    name: "Блейд",
    type: "Ассасин",
    hp: 1000,
    attack: 250,
    defense: 30,
    price: 250,
    image: "img/skins/blade.png",
  },
];
